version: '3.2'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --daemonize no
    ports:
      - 6379:6379
    networks:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=master

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 5051:8081
    networks:
      - redis
    depends_on:
      - redis
networks:
  redis:
    driver: bridge
